govCMS/scaffold

composer.9.json

GovCMS now has a `9.x` release published, move away from the POC namespace.

Move GovCMS distribution reference to new home

---

docker-compose.yml

Fixes invalid YAML syntax in docker-compose.yml file.
The issue is related to defining node anchors https://yaml.org/spec/1.2/spec.html#id2785586. The YAML spec says that the anchor name should be on the same line as the reference: x-lagoon-local-dev-url: &lagoon-local-dev-url

[GOVCMSD8-709] Fix YAML anchor syntax

---

.docker/Dockerfile.saasplus
custom/composer/composer.json

If a saasplus `composer.json` uses a repository other than one used in the root it will fail during dependency lookup.

Merge repositories values.

---

.lagoon.yml

- Updates cron to utilise the wrapper provided by scaffold tooling for alerting

[GOVCMS-5388]: Use notification wrapper for drush commands.

---

.gitignore

- Adds an ignore for `docker-compose.override.yml`

[GOVCMS-7435]: Add docker-compose.override.yml to .gitignore.

---

.gitlab-ci.paas.yml
composer.8.json
composer.9.json

- Add docker-compose.override.yml to ignore list
- Create private dirs when running build
- Asset packagist fix

Release 2.3.0

---

.docker/Dockerfile.paas

fixes GOVCMS-7732
Required govcms modules are added to `/app/web/sites/all` (see [here](https://github.com/govCMS/lagoon/blob/2.x-develop/.docker/Dockerfile.govcms#L51)), but the PaaS image has traditionally been removing the `/app` directory.
~~It seems like the base image is now leaner as per the comment and we can safely get rid of the line.~~
Added a line to copy the modules from the base image.

fix: add modules from base image

---

.ahoy.yml

This is in order to address this issue:
As you can see from the screenshot above, running `ahoy drush uinf` directly returns a wrapped username/email, which is hard to copy/paste or parse via grep. Whereas first ssh'ing via `ahoy cli` and then running `drush uinf` has the correctly-formatted, expected output.
This is not an issue with ahoy, rather than with docker-compose, and it can be fixed is you specify the `COLUMNS` parameter. I've set it to 120, which basically increases it from the default 80 and seems plenty (should fix the issue in most cases):

Prevent output wrapping when running "ahoy drush"

---

composer.8.json
composer.9.json

PaaS scaffolds are not working properly due to plugins not enabled. Copied the relevant bits from [govcms/lagoon](https://github.com/govCMS/lagoon/blob/10fb4c4977123c5931b6ee9ad9a95f1f48f4a89f/composer.json#L62).

fix: allow plugins for PaaS composer

---

.ahoy.yml
custom/ahoy.yml

This change causes an issue with running drush commands in Gitlab CI because it does not currently support tty (see: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2115).

[GOVCMS-8167] Revert "Prevent output wrapping when running "ahoy drush""

---

.lagoon.yml

With these conditionals, bulk deploys can now be done with straight-forward overrides allowing builds to skip the audit and config import tasks.
```graphql
mutation {
bulkDeployEnvironmentLatest(input: {
environments: [
{
buildVariables: [
{ name: "GOVCMS_SKIP_CONFIG_IMPORT" value: "true" },
{ name: "GOVCMS_SKIP_AUDIT" value: "true" }
]
environment: {
name: "master"
project: {name: "test-bulk-deploy"}
}
}
]
})
}
```

[GOVCMS-7646] Added lagoon conditionals for deploy overrides.

---

docker-compose.yml

- Adds a local clamav container
The ClamAV binary is being removed from the base images, to support scanning locally if required we'll bundle the clam container along with the local stack.

GOVCMS-5869: ClamAV support

---

docker-compose.yml

- Updates the networks configuration to attach the other containers to the `amazeeio-network` to use tools provided (eg. mailhog)

Fix: Add missing network stanzas.

---

.ahoy.yml

`nginx` needs to be restarted to have the stack working properly when other containers are restarted. Without this, we see 503.

Fixed 'ahoy debug' command not restarting nginx.

---

composer.10.json

egulias/email-validator is no longer required after removal of Swiftmailer.

Remove egulias/email-validator

---

.docker/Dockerfile.paas

Historically modules have been copied from the `govcms/lagoon` base images: https://github.com/govCMS/lagoon/tree/3.x-develop/modules as there were additional, required custom modules maintained here.
This is no longer the case, it should be safe to remove this extra step in the build. Tested in `sandbox/govcms-10295-test`

[GOVCMS-10295] Removed extra `COPY` from PaaS dockerfile

---

composer.10.json

php-http/discovery plugin is needed as part of the update to core 10.2

Add php-http/discovery to the composer allow-plugins

---

docker-compose.yml

The following pull request will add support for pygmy mailhog particularly on mac:
https://github.com/uselagoon/lagoon-images/pull/1073
This revert will allow multiple local sites to be run.
Fixes #94

Fix: Remove network configuration for local containers

---

.docker/Dockerfile.paas

When provisioning PaaS projects, all the scaffold modules from [govcms/lagoon](https://github.com/govCMS/lagoon/tree/f7ed6cd09b97172cda728fa25f3504c716e1d577/modules) were getting deleted and was thus failing new project creations.
This PR updates the Dockerfile and preserves the modules directory and restores it after `composer install`.

Preserve scaffold modules in PaaS

---

.docker/Dockerfile.saasplus

Since the SaaS+ Dockerfile contains a `composer install`, it would make sense to require a GITHUB_TOKEN from users, however we could prevent the build from failing right away if one is not provided.

Conditionally add github token for composer

---

.docker/Dockerfile.test

The PHP8.3 base images move Drush and it is no longer available via `/usr/local/bin`. Drush is installed by composer and is available in the vendor directory which is copied above this continues to resolve correctly after the PHP upgrade.
```
configured lagoon-php.ini
Drush Launcher Version: 0.10.2
Drush Commandline Tool 12.5.2.0
configured lagoon-php.ini
/usr/local/bin/drush
```

Fix: Remove additional copies.

---

docker-compose.yml

Although new projects created on the GovCMS platform already had the correct environment variables, locally the ClamAV ones were still being used. This is now fixed and `httpav` will now work properly locally.

[DEVOPS-631] Replace clamav vars with httpav's

---

composer.10.json

The plugin tbachert/spi is not required as part of open-telemetry/sdk
[open-telemetry/sdk - Packagist](https://packagist.org/packages/open-telemetry/sdk)  which is part of Drupal core.
Adding this plugin to allowed plugins.

[GOVCMSD10-1102] Add plugin tbachert/spi to Scaffold

---

.gitlab-ci.paas.yml

New PaaS provisions currently fail since they use the legacy CI image (govcms/govcms-ci) and therefore Pipelines fail due to not having the latest PHP version. This change allows them to work again.

fix: use latest CI image for new PaaS provisions
